import type { WeeklySummaryData, EolReportData, AlertReportData, HostInventoryData } from "./report-data.js";

const NAVY = "#1B3A5C";
const SEVERITY_COLORS: Record<string, string> = {
  critical: "#DC2626", high: "#EA580C", medium: "#D97706", low: "#2563EB", info: "#6B7280",
};
const ROW_ALT = "#F8FAFC";

function baseStyles(): string {
  return `
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1E293B; margin: 0; padding: 0; font-size: 12px; line-height: 1.5; }
    .page { padding: 40px 50px; page-break-after: always; }
    .page:last-child { page-break-after: auto; }
    h1 { color: ${NAVY}; font-size: 24px; margin: 0 0 8px 0; }
    h2 { color: ${NAVY}; font-size: 18px; margin: 24px 0 12px 0; border-bottom: 2px solid ${NAVY}; padding-bottom: 4px; }
    h3 { color: ${NAVY}; font-size: 14px; margin: 16px 0 8px 0; }
    .subtitle { color: #64748B; font-size: 13px; margin-bottom: 20px; }
    .executive { background: #F1F5F9; padding: 16px 20px; border-radius: 8px; margin: 16px 0; border-left: 4px solid ${NAVY}; font-size: 13px; }
    .metrics-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
    .metric-card { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 6px; padding: 12px; text-align: center; }
    .metric-value { font-size: 28px; font-weight: 700; color: ${NAVY}; }
    .metric-label { font-size: 11px; color: #64748B; text-transform: uppercase; letter-spacing: 0.5px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 11px; }
    th { background: ${NAVY}; color: white; text-align: left; padding: 8px 12px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 6px 12px; border-bottom: 1px solid #E2E8F0; }
    tr:nth-child(even) td { background: ${ROW_ALT}; }
    .severity-badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: 600; color: white; text-transform: uppercase; }
    .footer { text-align: center; color: #94A3B8; font-size: 10px; margin-top: 30px; padding-top: 12px; border-top: 1px solid #E2E8F0; }
    .bar-chart { display: flex; align-items: flex-end; gap: 4px; height: 100px; margin: 12px 0; }
    .bar { background: ${NAVY}; border-radius: 3px 3px 0 0; min-width: 28px; text-align: center; }
    .bar-label { font-size: 9px; color: #64748B; margin-top: 4px; text-align: center; }
    .bar-value { font-size: 9px; color: white; padding: 2px 0; }
    .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
  `;
}

function footer(timestamp: string): string {
  return `<div class="footer">Generated by InfraWatch &middot; ${new Date(timestamp).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })} &middot; Confidential</div>`;
}

function severityBadge(severity: string): string {
  const color = SEVERITY_COLORS[severity] ?? SEVERITY_COLORS.info;
  return `<span class="severity-badge" style="background:${color}">${severity}</span>`;
}

function barChart(items: Array<{ label: string; value: number }>, color = NAVY): string {
  const maxVal = Math.max(...items.map((i) => i.value), 1);
  return `<div class="bar-chart">${items.map((item) => {
    const h = Math.max((item.value / maxVal) * 100, 4);
    return `<div style="flex:1;text-align:center"><div class="bar" style="height:${h}px;background:${color}"><div class="bar-value">${item.value}</div></div><div class="bar-label">${item.label}</div></div>`;
  }).join("")}</div>`;
}

// ─── Weekly Summary ───

export function renderWeeklySummary(data: WeeklySummaryData): string {
  const now = new Date().toISOString();
  const periodStr = `${new Date(data.period.start).toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${new Date(data.period.end).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;

  const totalNewAlerts = Object.values(data.alerts.newBySeverity).reduce((a, b) => a + b, 0);
  const executive = `During the week of ${periodStr}, InfraWatch monitored ${data.overview.activeHosts} active hosts with ${data.overview.totalPackages.toLocaleString()} packages. ${totalNewAlerts} new alerts were raised${data.alerts.newBySeverity.critical ? ` (${data.alerts.newBySeverity.critical} critical)` : ""} and ${data.alerts.resolved} were resolved. ${data.eol.pastEol} products are past end-of-life.`;

  const sevItems = ["critical", "high", "medium", "low"].map((s) => ({
    label: s.charAt(0).toUpperCase() + s.slice(1),
    value: data.alerts.newBySeverity[s] ?? 0,
  }));

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${baseStyles()}</style></head><body>
    <!-- Page 1: Executive -->
    <div class="page">
      <h1>Weekly Infrastructure Report</h1>
      <div class="subtitle">${periodStr}</div>
      <div class="executive">${executive}</div>
      <div class="metrics-grid">
        <div class="metric-card"><div class="metric-value">${data.overview.activeHosts}</div><div class="metric-label">Active Hosts</div></div>
        <div class="metric-card"><div class="metric-value">${data.overview.totalPackages.toLocaleString()}</div><div class="metric-label">Packages</div></div>
        <div class="metric-card"><div class="metric-value">${totalNewAlerts}</div><div class="metric-label">New Alerts</div></div>
        <div class="metric-card"><div class="metric-value">${data.changes.total}</div><div class="metric-label">Changes</div></div>
      </div>
      <div class="two-col">
        <div>
          <h3>Alert Severity Distribution</h3>
          ${barChart(sevItems.map((s, i) => ({ ...s, label: s.label })), ["#DC2626", "#EA580C", "#D97706", "#2563EB"][0])}
          ${barChart(sevItems)}
        </div>
        <div>
          <h3>Hosts by Environment</h3>
          ${data.hostsByEnvironment.length > 0
            ? barChart(data.hostsByEnvironment.slice(0, 8).map((e) => ({ label: e.environment.slice(0, 10), value: e.count })))
            : "<p>No environment tags configured.</p>"}
        </div>
      </div>
      ${footer(now)}
    </div>

    <!-- Page 2: Alerts & Changes -->
    <div class="page">
      <h2>Top Vulnerability Alerts</h2>
      <table>
        <tr><th>Package</th><th>Severity</th><th>Hosts</th></tr>
        ${data.alerts.topPackages.slice(0, 10).map((p) => `<tr><td>${esc(p.packageName)}</td><td>${p.count} alerts</td><td>—</td></tr>`).join("")}
      </table>

      <h2>Top Outdated Packages</h2>
      <table>
        <tr><th>Package</th><th>Current</th><th>Available</th><th>Hosts</th></tr>
        ${data.topOutdatedPackages.map((p) => `<tr><td>${esc(p.packageName)}</td><td>${esc(p.currentVersion)}</td><td>${esc(p.availableVersion)}</td><td>${p.hostCount}</td></tr>`).join("")}
      </table>
      ${footer(now)}
    </div>

    <!-- Page 3: EOL & Stale -->
    <div class="page">
      <h2>EOL Warnings</h2>
      <div class="metrics-grid" style="grid-template-columns: repeat(3, 1fr);">
        <div class="metric-card"><div class="metric-value" style="color:#DC2626">${data.eol.pastEol}</div><div class="metric-label">Past EOL</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#EA580C">${data.eol.upcomingEol}</div><div class="metric-label">Upcoming (90d)</div></div>
        <div class="metric-card"><div class="metric-value">${data.eol.newItems}</div><div class="metric-label">New This Period</div></div>
      </div>

      <h2>Stale Hosts</h2>
      ${data.staleHosts.length > 0 ? `<table><tr><th>Hostname</th><th>Last Seen</th></tr>
        ${data.staleHosts.map((h) => `<tr><td>${esc(h.hostname)}</td><td>${new Date(h.lastSeenAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</td></tr>`).join("")}
      </table>` : "<p>No stale hosts.</p>"}

      <h2>Recent Changes (Top 20)</h2>
      <table>
        <tr><th>Event</th><th>Host</th><th>Summary</th></tr>
        ${data.changes.significant.map((c) => `<tr><td>${esc(c.eventType.replace(/_/g, " "))}</td><td>${esc(c.hostname)}</td><td>${esc(c.summary.slice(0, 80))}</td></tr>`).join("")}
      </table>
      ${footer(now)}
    </div>
  </body></html>`;
}

// ─── EOL Report ───

export function renderEolReport(data: EolReportData): string {
  const now = new Date().toISOString();
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${baseStyles()}</style></head><body>
    <div class="page">
      <h1>End-of-Life Report</h1>
      <div class="subtitle">${new Date(data.period.start).toLocaleDateString("en-US", { dateStyle: "medium" })} – ${new Date(data.period.end).toLocaleDateString("en-US", { dateStyle: "medium" })}</div>
      <div class="metrics-grid">
        <div class="metric-card"><div class="metric-value" style="color:#DC2626">${data.summary.pastEol}</div><div class="metric-label">Past EOL</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#EA580C">${data.summary.upcomingEol}</div><div class="metric-label">Upcoming (90d)</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#D97706">${data.summary.within6Months}</div><div class="metric-label">Within 6 Months</div></div>
        <div class="metric-card"><div class="metric-value">${data.summary.totalActive}</div><div class="metric-label">Total Active</div></div>
      </div>
      ${data.byCategory.length > 0 ? `<h3>By Category</h3>${barChart(data.byCategory.map((c) => ({ label: c.category, value: c.count })))}` : ""}
      <h3>Most Affected Hosts</h3>
      <table><tr><th>Hostname</th><th>EOL Count</th></tr>
        ${data.mostAffectedHosts.map((h) => `<tr><td>${esc(h.hostname)}</td><td>${h.eolCount}</td></tr>`).join("")}
      </table>
      ${footer(now)}
    </div>
    <div class="page">
      <h2>EOL Alert Details</h2>
      <table>
        <tr><th>Product</th><th>Version</th><th>EOL Date</th><th>Days</th><th>Host</th><th>Successor</th><th>Category</th></tr>
        ${data.alerts.map((a) => `<tr>
          <td>${esc(a.productName)}</td><td>${esc(a.installedVersion)}</td>
          <td>${new Date(a.eolDate).toLocaleDateString("en-US")}</td>
          <td style="color:${a.daysPastEol > 0 ? "#DC2626" : "#EA580C"}">${a.daysPastEol > 0 ? `${a.daysPastEol}d past` : `${Math.abs(a.daysPastEol)}d left`}</td>
          <td>${esc(a.hostname)}</td><td>${esc(a.successorVersion ?? "—")}</td><td>${esc(a.productCategory)}</td>
        </tr>`).join("")}
      </table>
      ${footer(now)}
    </div>
  </body></html>`;
}

// ─── Alert Report ───

export function renderAlertReport(data: AlertReportData): string {
  const now = new Date().toISOString();
  const sevItems = ["critical", "high", "medium", "low"].map((s) => ({
    label: s.charAt(0).toUpperCase() + s.slice(1), value: (data.summary as Record<string, number>)[s] ?? 0,
  }));

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${baseStyles()}</style></head><body>
    <div class="page">
      <h1>Alert Report</h1>
      <div class="subtitle">${new Date(data.period.start).toLocaleDateString("en-US", { dateStyle: "medium" })} – ${new Date(data.period.end).toLocaleDateString("en-US", { dateStyle: "medium" })}</div>
      <div class="metrics-grid">
        <div class="metric-card"><div class="metric-value">${data.summary.total}</div><div class="metric-label">Total New</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#DC2626">${data.summary.critical}</div><div class="metric-label">Critical</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#EA580C">${data.summary.high}</div><div class="metric-label">High</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#16A34A">${data.summary.resolved}</div><div class="metric-label">Resolved</div></div>
      </div>
      <h3>Severity Distribution</h3>
      ${barChart(sevItems)}
      <h2>Most Widespread Vulnerabilities</h2>
      <table><tr><th>Package</th><th>Severity</th><th>Hosts Affected</th></tr>
        ${data.topVulnerable.map((v) => `<tr><td>${esc(v.packageName)}</td><td>${severityBadge(v.severity)}</td><td>${v.hostCount}</td></tr>`).join("")}
      </table>
      ${footer(now)}
    </div>
    <div class="page">
      <h2>New Alerts</h2>
      <table>
        <tr><th>Package</th><th>Severity</th><th>Host</th><th>Current</th><th>Available</th><th>Date</th></tr>
        ${data.newAlerts.map((a) => `<tr>
          <td>${esc(a.packageName)}</td><td>${severityBadge(a.severity)}</td><td>${esc(a.hostname)}</td>
          <td>${esc(a.currentVersion ?? "—")}</td><td>${esc(a.availableVersion ?? "—")}</td>
          <td>${new Date(a.createdAt).toLocaleDateString("en-US")}</td>
        </tr>`).join("")}
      </table>
      ${footer(now)}
    </div>
  </body></html>`;
}

// ─── Host Inventory ───

export function renderHostInventory(data: HostInventoryData): string {
  const now = data.generatedAt;
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${baseStyles()}</style></head><body>
    <div class="page">
      <h1>Host Inventory Report</h1>
      <div class="subtitle">Generated ${new Date(now).toLocaleDateString("en-US", { dateStyle: "medium", })}</div>
      <div class="metrics-grid" style="grid-template-columns: repeat(5, 1fr);">
        <div class="metric-card"><div class="metric-value">${data.summary.totalHosts}</div><div class="metric-label">Total Hosts</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#16A34A">${data.summary.active}</div><div class="metric-label">Active</div></div>
        <div class="metric-card"><div class="metric-value" style="color:#D97706">${data.summary.stale}</div><div class="metric-label">Stale</div></div>
        <div class="metric-card"><div class="metric-value">${data.summary.totalPackages.toLocaleString()}</div><div class="metric-label">Packages</div></div>
        <div class="metric-card"><div class="metric-value">${data.summary.totalServices}</div><div class="metric-label">Services</div></div>
      </div>
    </div>
    <div class="page">
      <h2>All Hosts</h2>
      <table>
        <tr><th>Hostname</th><th>IP</th><th>OS</th><th>Status</th><th>Last Seen</th><th>Pkgs</th><th>Svcs</th><th>Env</th></tr>
        ${data.hosts.map((h) => `<tr>
          <td><strong>${esc(h.hostname)}</strong></td><td>${esc(h.ip ?? "—")}</td>
          <td>${esc(h.os ?? "")} ${esc(h.osVersion ?? "")}</td>
          <td><span style="color:${h.status === "active" ? "#16A34A" : "#D97706"}">${h.status}</span></td>
          <td>${new Date(h.lastSeenAt).toLocaleDateString("en-US")}</td>
          <td>${h.packageCount}</td><td>${h.serviceCount}</td><td>${esc(h.environmentTag ?? "—")}</td>
        </tr>`).join("")}
      </table>
      ${footer(now)}
    </div>
  </body></html>`;
}

/** Escape HTML entities */
function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
